### ISSUE TITLE
Structure-from-Motion result does not show in 3D Viewer

### ISSUE THREAD

**Issue by dermaktor** [ryanfb/homebrew-alicevision#4]
I was able to successfully install following the updated version of https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html.
However, when I compute StructureFromMotion, after successful completion, the 3D Viewer does not load the result.
Strange enough, if I follow through until Texturing, the load button appears and when I click on it, the the textured mesh shows just fine.
What I noticed in the console:
`
[1/5] CameraInit
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 206, in run
    self.updateStats()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 200, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 163, in update
    self.process.update(proc)
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 118, in update
    data = proc.as_dict(self.dynamicKeys)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'

 - commandLine: aliceVision_cameraInit  --sensorDatabase "/usr/local/Cellar/alicevision/2.1.0/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/Users/dawandeh/Documents/MeshroomCache/CameraInit/4ef6f9e0bdbb8d10b96123820c3649bd9bf447fb/cameraInit.sfm" --allowSingleView 1  --input "/Users/dawandeh/Documents/MeshroomCache/CameraInit/4ef6f9e0bdbb8d10b96123820c3649bd9bf447fb//viewpoints.sfm"
 - logFile: /Users/dawandeh/Documents/MeshroomCache/CameraInit/4ef6f9e0bdbb8d10b96123820c3649bd9bf447fb/log
 - elapsed time: 0:00:00.088005

[2/5] FeatureExtraction
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 206, in run
    self.updateStats()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 200, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 163, in update
    self.process.update(proc)
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 118, in update
    data = proc.as_dict(self.dynamicKeys)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'

 - commandLine: aliceVision_featureExtraction  --input "/Users/dawandeh/Documents/MeshroomCache/CameraInit/4ef6f9e0bdbb8d10b96123820c3649bd9bf447fb/cameraInit.sfm" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output "/Users/dawandeh/Documents/MeshroomCache/FeatureExtraction/03020b4b7d60d330d3b21b209f68efc2655fc5ec" --rangeStart 0 --rangeSize 7
 - logFile: /Users/dawandeh/Documents/MeshroomCache/FeatureExtraction/03020b4b7d60d330d3b21b209f68efc2655fc5ec/0.log
 - elapsed time: 0:01:39.338543

[3/5] ImageMatching
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 206, in run
    self.updateStats()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 200, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 163, in update
    self.process.update(proc)
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 118, in update
    data = proc.as_dict(self.dynamicKeys)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'

 - commandLine: aliceVision_imageMatching  --input "/Users/dawandeh/Documents/MeshroomCache/CameraInit/4ef6f9e0bdbb8d10b96123820c3649bd9bf447fb/cameraInit.sfm" --featuresFolders "/Users/dawandeh/Documents/MeshroomCache/FeatureExtraction/03020b4b7d60d330d3b21b209f68efc2655fc5ec" --tree "/usr/local/Cellar/alicevision/2.1.0/share/aliceVision/vlfeat_K80L3.SIFT.tree" --weights "" --minNbImages 200 --maxDescriptors 500 --nbMatches 50 --verboseLevel info --output "/Users/dawandeh/Documents/MeshroomCache/ImageMatching/f3a9afdbbc04df611f7957436a31f728b67f913e/imageMatches.txt" 
 - logFile: /Users/dawandeh/Documents/MeshroomCache/ImageMatching/f3a9afdbbc04df611f7957436a31f728b67f913e/log
 - elapsed time: 0:00:00.064649

[4/5] FeatureMatching
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 206, in run
    self.updateStats()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 200, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 163, in update
    self.process.update(proc)
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 118, in update
    data = proc.as_dict(self.dynamicKeys)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'

 - commandLine: aliceVision_featureMatching  --input "/Users/dawandeh/Documents/MeshroomCache/CameraInit/4ef6f9e0bdbb8d10b96123820c3649bd9bf447fb/cameraInit.sfm" --featuresFolders "/Users/dawandeh/Documents/MeshroomCache/FeatureExtraction/03020b4b7d60d330d3b21b209f68efc2655fc5ec" --imagePairsList "/Users/dawandeh/Documents/MeshroomCache/ImageMatching/f3a9afdbbc04df611f7957436a31f728b67f913e/imageMatches.txt" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --geometricError 0.0 --maxMatches 0 --savePutativeMatches False --guidedMatching False --exportDebugFiles False --verboseLevel info --output "/Users/dawandeh/Documents/MeshroomCache/FeatureMatching/cdfeeba90b9dd8035420f7ce0fd3ee3a7c540b66" --rangeStart 0 --rangeSize 7
 - logFile: /Users/dawandeh/Documents/MeshroomCache/FeatureMatching/cdfeeba90b9dd8035420f7ce0fd3ee3a7c540b66/0.log
 - elapsed time: 0:00:09.466333

[5/5] StructureFromMotion
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 206, in run
    self.updateStats()
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 200, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 163, in update
    self.process.update(proc)
  File "/Users/dawandeh/Downloads/meshroom-2019.1.0/meshroom/core/stats.py", line 118, in update
    data = proc.as_dict(self.dynamicKeys)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'
`

I can't figure out how to fix this.

**Comment by ryanfb** [comment]
This issue tracker is more for specific issues with building the Homebrew formula - I'd suggest you instead file this same issue upstream at <https://github.com/alicevision/AliceVision/issues>. Thanks!
